FROM node:22-alpine AS build
WORKDIR /web
ARG VITE_GA_MEASUREMENT_ID
ARG VITE_ADSENSE_MODE=test
ARG VITE_ADSENSE_CALCULATORS_CLIENT
ARG VITE_ADSENSE_CALCULATORS_LEADERBOARD
ARG VITE_ADSENSE_CALCULATORS_SIDEBAR
ARG VITE_ADSENSE_CALCULATORS_RESULTS
ARG VITE_ADSENSE_TIME_CLIENT
ARG VITE_ADSENSE_TIME_LEADERBOARD
ARG VITE_ADSENSE_TIME_SIDEBAR
ARG VITE_ADSENSE_TIME_RESULTS
ARG VITE_ADSENSE_SEO_CLIENT
ARG VITE_ADSENSE_SEO_LEADERBOARD
ARG VITE_ADSENSE_SEO_SIDEBAR
ARG VITE_ADSENSE_SEO_RESULTS
ENV VITE_GA_MEASUREMENT_ID=$VITE_GA_MEASUREMENT_ID VITE_ADSENSE_MODE=$VITE_ADSENSE_MODE VITE_ADSENSE_CALCULATORS_CLIENT=$VITE_ADSENSE_CALCULATORS_CLIENT VITE_ADSENSE_CALCULATORS_LEADERBOARD=$VITE_ADSENSE_CALCULATORS_LEADERBOARD VITE_ADSENSE_CALCULATORS_SIDEBAR=$VITE_ADSENSE_CALCULATORS_SIDEBAR VITE_ADSENSE_CALCULATORS_RESULTS=$VITE_ADSENSE_CALCULATORS_RESULTS VITE_ADSENSE_TIME_CLIENT=$VITE_ADSENSE_TIME_CLIENT VITE_ADSENSE_TIME_LEADERBOARD=$VITE_ADSENSE_TIME_LEADERBOARD VITE_ADSENSE_TIME_SIDEBAR=$VITE_ADSENSE_TIME_SIDEBAR VITE_ADSENSE_TIME_RESULTS=$VITE_ADSENSE_TIME_RESULTS VITE_ADSENSE_SEO_CLIENT=$VITE_ADSENSE_SEO_CLIENT VITE_ADSENSE_SEO_LEADERBOARD=$VITE_ADSENSE_SEO_LEADERBOARD VITE_ADSENSE_SEO_SIDEBAR=$VITE_ADSENSE_SEO_SIDEBAR VITE_ADSENSE_SEO_RESULTS=$VITE_ADSENSE_SEO_RESULTS
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /web/dist /usr/share/nginx/html
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 CMD wget --spider -q http://127.0.0.1/ || exit 1
