import { useState } from "react";
import type { JsonValue } from "../../types";

function label(key: string): string { return key.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function format(key: string, value: JsonValue): string { if (typeof value === "number") { if (key.includes("percent") || key.includes("rate")) return `${value.toLocaleString()}%`; if (key.includes("gbp") || key.includes("cost") || key.includes("salary") || key.includes("income")) return new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format(value); return value.toLocaleString(); } return typeof value === "object" ? JSON.stringify(value, null, 2) : String(value); }

export function ResultsDisplay({ results, disclaimer, cached = false }: { results: Record<string, JsonValue>; disclaimer: string; cached?: boolean }): JSX.Element {
  const [notice, setNotice] = useState(""); const text = Object.entries(results).map(([key, value]) => `${label(key)}: ${format(key, value)}`).join("\n");
  async function copy(): Promise<void> { await navigator.clipboard?.writeText(text); setNotice("Copied to clipboard"); }
  async function share(): Promise<void> { const supportsSharing = "share" in navigator; if (supportsSharing) await navigator.share({ title: "Calculator result", text }); else await copy(); setNotice(supportsSharing ? "Share sheet opened" : "Copied to clipboard"); }
  return <section aria-live="polite" className="mt-6 rounded-xl border border-indigo-200 bg-indigo-50 p-5 dark:border-indigo-900 dark:bg-indigo-950/50"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Your result</h2><div className="flex gap-2"><button type="button" onClick={() => void copy()} className="rounded border border-indigo-300 px-2 py-1 text-xs">Copy</button><button type="button" onClick={() => void share()} className="rounded border border-indigo-300 px-2 py-1 text-xs">Share</button><span className="self-center text-xs text-slate-500">{cached ? "Cached" : "Fresh"}</span></div></div>{notice && <p className="mb-3 text-xs text-green-700 dark:text-green-300">{notice}</p>}<dl className="grid gap-3 sm:grid-cols-2">{Object.entries(results).map(([key, value]) => <div key={key} className="rounded-lg bg-white p-3 dark:bg-slate-900"><dt className="text-xs uppercase tracking-wide text-slate-500">{label(key)}</dt><dd className="mt-1 break-words font-medium">{typeof value === "object" ? <pre className="max-h-40 overflow-auto text-xs">{format(key, value)}</pre> : format(key, value)}</dd></div>)}</dl><p className="mt-4 text-xs text-slate-500">{disclaimer}</p></section>;
}
