import type { ToolDefinition } from "../../types";
import { AgeCalculatorPage } from "./AgeCalculatorPage";
import { CountdownTimerPage } from "./CountdownTimerPage";
import { TimeZoneConverterPage } from "./TimeZoneConverterPage";

const timeTools: readonly ToolDefinition[] = [
  { slug: "timezone-converter", title: "Timezone Converter", description: "Compare an instant across IANA timezones and see 200 current global times.", endpoint: "/api/v1/tools/time/timezone-converter", fields: [{ name: "source_timezone", label: "Source timezone", type: "text", defaultValue: "America/New_York", required: true }, { name: "target_timezone", label: "Target timezone", type: "text", defaultValue: "Europe/London", required: true }, { name: "date_time", label: "Date and time", type: "datetime-local", defaultValue: "2026-08-07T14:30", required: true }] },
  { slug: "age-calculator", title: "Age Calculator", description: "Calculate your exact calendar age, zodiac sign, and next birthday.", endpoint: "/api/v1/tools/time/age-calculator", fields: [{ name: "birthdate", label: "Birth date", type: "date", defaultValue: "1990-05-15", required: true }] },
  { slug: "countdown-timer", title: "Countdown Timer", description: "Create a human-readable countdown to an important event.", endpoint: "/api/v1/tools/time/countdown-timer", fields: [{ name: "target_date", label: "Target date", type: "datetime-local", defaultValue: "2030-01-01T00:00", required: true }, { name: "event_name", label: "Event name", type: "text", defaultValue: "New Year" }, { name: "timezone", label: "Timezone", type: "text", defaultValue: "Europe/London", required: true }, { name: "start_date", label: "Start date (optional, for progress)", type: "datetime-local" }] }
];

export function TimeToolsPage({ slug }: { slug?: string }): JSX.Element { const pages: Record<string, JSX.Element> = { "timezone-converter": <TimeZoneConverterPage />, "age-calculator": <AgeCalculatorPage />, "countdown-timer": <CountdownTimerPage /> }; if (slug && pages[slug]) return pages[slug]; return <section><p className="text-sm font-semibold uppercase tracking-widest text-indigo-600">time.kalko.uk</p><h1 className="mt-3 text-4xl font-bold tracking-tight">Time, made clear.</h1><div className="mt-8 grid gap-4 sm:grid-cols-3">{timeTools.map((tool) => <a key={tool.slug} href={`#/${tool.slug}`} className="rounded-xl border border-slate-200 bg-white p-5 hover:border-indigo-400 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">{tool.title}</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{tool.description}</p></a>)}</div></section>; }
