import { useMemo, useState } from "react";
import { trackToolUsed } from "../../analytics/ga4";
import { ageFromDate } from "./timeUtils";

const zodiac = (value: string): string => { const date = new Date(`${value}T00:00:00`); const month = date.getMonth() + 1; const day = date.getDate(); const signs = [[1, 20, "Aquarius"], [2, 19, "Pisces"], [3, 21, "Aries"], [4, 20, "Taurus"], [5, 21, "Gemini"], [6, 21, "Cancer"], [7, 23, "Leo"], [8, 23, "Virgo"], [9, 23, "Libra"], [10, 23, "Scorpio"], [11, 22, "Sagittarius"], [12, 22, "Capricorn"]] as const; return signs.find(([signMonth, signDay]) => month < signMonth || (month === signMonth && day < signDay))?.[2] ?? "Capricorn"; };

export function AgeCalculatorTool(): JSX.Element {
  const [birthdate, setBirthdate] = useState("1990-05-15"); const [reference, setReference] = useState(""); const result = useMemo(() => ageFromDate(birthdate, reference ? new Date(`${reference}T23:59:59`) : new Date()), [birthdate, reference]); const nextBirthday = useMemo(() => { if (!result) return null; const now = reference ? new Date(`${reference}T00:00:00`) : new Date(); const birthday = new Date(now.getFullYear(), new Date(`${birthdate}T00:00:00`).getMonth(), new Date(`${birthdate}T00:00:00`).getDate()); if (birthday < now) birthday.setFullYear(now.getFullYear() + 1); return Math.ceil((birthday.getTime() - now.getTime()) / 86_400_000); }, [birthdate, reference, result]);
  const updateBirthdate = (value: string): void => { setBirthdate(value); const next = ageFromDate(value, reference ? new Date(`${reference}T23:59:59`) : new Date()); if (next) trackToolUsed("time", "age-calculator", { age_years: next.years, total_days_lived: next.totalDays }); };
  return <section><div className="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-2"><label className="text-sm font-medium">Birth date<input type="date" value={birthdate} max={new Date().toISOString().slice(0, 10)} onChange={(event) => updateBirthdate(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3 dark:border-slate-700 dark:bg-slate-950" /></label><label className="text-sm font-medium">Reference date <span className="font-normal text-slate-500">(optional)</span><input type="date" value={reference} onChange={(event) => setReference(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3 dark:border-slate-700 dark:bg-slate-950" /></label></div>{!result ? <p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">Enter a birth date before the reference date.</p> : <div aria-live="polite" className="mt-6 rounded-xl border border-indigo-200 bg-indigo-50 p-6 dark:border-indigo-900 dark:bg-indigo-950/40"><p className="text-sm text-slate-600 dark:text-slate-300">You are</p><p className="mt-1 text-3xl font-bold tracking-tight">{result.years} years, {result.months} months, {result.days} days old</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Fact label="Zodiac sign" value={zodiac(birthdate)} /><Fact label="Next birthday" value={`${nextBirthday ?? 0} days`} /><Fact label="Fun fact" value={`You've lived ${result.totalDays.toLocaleString()} days!`} /></div></div>}</section>;
}
function Fact({ label, value }: { label: string; value: string }): JSX.Element { return <div className="rounded-lg bg-white p-4 dark:bg-slate-900"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
