import { useEffect, useMemo, useState } from "react";
import { MAJOR_TIMEZONES, remainingTo } from "./timeUtils";
import { trackToolUsed } from "../../analytics/ga4";

interface SavedCountdown { eventName: string; target: string; timezone: string; startedAt: number; }
const STORAGE_KEY = "calculator-tools-countdown";
function load(): SavedCountdown { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) ?? "") as SavedCountdown; } catch { return { eventName: "", target: "2030-01-01T00:00", timezone: "Europe/London", startedAt: Date.now() }; } }
function alertTone(): void { const context = new AudioContext(); const oscillator = context.createOscillator(); oscillator.connect(context.destination); oscillator.frequency.value = 880; oscillator.start(); oscillator.stop(context.currentTime + .2); }

export function CountdownTimerTool(): JSX.Element {
  const saved = useMemo(load, []); const [eventName, setEventName] = useState(saved.eventName); const [target, setTarget] = useState(saved.target); const [timezone, setTimezone] = useState(saved.timezone); const [startedAt, setStartedAt] = useState(saved.startedAt); const [, setNow] = useState(Date.now()); const [completed, setCompleted] = useState(false);
  useEffect(() => { const id = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(id); }, []); const remaining = remainingTo(target); const total = Math.max(1, new Date(target).getTime() - startedAt); const progress = Math.min(100, Math.max(0, (1 - remaining.total * 1000 / total) * 100));
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify({ eventName, target, timezone, startedAt })); }, [eventName, target, timezone, startedAt]); useEffect(() => { if (remaining.total === 0 && !completed) { setCompleted(true); try { alertTone(); } catch { /* Browser audio policy can block this. */ } } }, [completed, remaining.total]);
  const units: Array<[string, number]> = [["Days", remaining.days], ["Hours", remaining.hours], ["Minutes", remaining.minutes], ["Seconds", remaining.seconds]];
  const updateTarget = (value: string): void => { setTarget(value); setStartedAt(Date.now()); setCompleted(false); trackToolUsed("time", "countdown-timer", { target_configured: true }); };
  return <section><div className="grid gap-4 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-2"><label className="text-sm font-medium">Event name <span className="font-normal text-slate-500">(optional)</span><input value={eventName} onChange={(event) => setEventName(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3 dark:border-slate-700 dark:bg-slate-950" /></label><label className="text-sm font-medium">Timezone<select value={timezone} onChange={(event) => setTimezone(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3 dark:border-slate-700 dark:bg-slate-950">{MAJOR_TIMEZONES.map((zone) => <option key={zone}>{zone}</option>)}</select></label><label className="text-sm font-medium sm:col-span-2">Target date and time<input type="datetime-local" value={target} onChange={(event) => updateTarget(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3 dark:border-slate-700 dark:bg-slate-950" /></label></div><div aria-live="assertive" className="mt-6 rounded-xl border border-indigo-200 bg-indigo-50 p-6 dark:border-indigo-900 dark:bg-indigo-950/40"><p className="text-sm text-slate-600 dark:text-slate-300">{eventName ? `Countdown to ${eventName}` : "Countdown"}</p><div className="mt-4 grid grid-cols-4 gap-2 text-center">{units.map(([label, value]) => <div key={label} className="rounded-lg bg-white p-3 dark:bg-slate-900"><strong className="block text-2xl">{String(value).padStart(2, "0")}</strong><span className="text-xs text-slate-500">{label}</span></div>)}</div><div className="mt-6 h-3 overflow-hidden rounded-full bg-white dark:bg-slate-900"><div className="h-full bg-indigo-600 transition-[width] duration-1000" style={{ width: `${progress}%` }} aria-label={`${Math.round(progress)} percent complete`} /></div><p className="mt-2 text-right text-xs text-slate-500">{Math.round(progress)}% complete · saved on this device</p>{remaining.total === 0 && <p className="mt-4 font-semibold text-indigo-700 dark:text-indigo-300">Your countdown is complete.</p>}</div></section>;
}
