import { useEffect, useMemo, useState } from "react";
import { calculate } from "../../api/client";
import { trackToolUsed } from "../../analytics/ga4";
import { csv, downloadCsv, MIN_WORDS, words } from "./seoUtils";
import type { JsonValue } from "../../types";

interface KeywordResult { total_words: number; keyword_count: number; keyword_density_percent: number; top_10_keywords: Array<{ keyword: string; count: number }>; recommendations: string[]; }
export function KeywordDensityTool(): JSX.Element {
  const [text, setText] = useState(""); const [focusKeyword, setFocusKeyword] = useState(""); const [includeStopWords, setIncludeStopWords] = useState(false); const [result, setResult] = useState<KeywordResult | null>(null); const [error, setError] = useState(""); const count = words(text).length;
  useEffect(() => { if (count < MIN_WORDS) { setResult(null); return; } const timer = window.setTimeout(() => void calculate<KeywordResult & Record<string, JsonValue>>("/api/v1/tools/seo/keyword-density", { text, ...(focusKeyword.trim() ? { focus_keyword: focusKeyword.trim() } : {}) }).then((response) => { setResult(response.result); setError(""); trackToolUsed("seo", "keyword-density", response.result); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Keyword analysis is unavailable.")), 400); return () => window.clearTimeout(timer); }, [count, focusKeyword, text]);
  const displayKeywords = useMemo(() => { if (!includeStopWords) return result?.top_10_keywords ?? []; const counts = new Map<string, number>(); words(text).forEach((word) => counts.set(word, (counts.get(word) ?? 0) + 1)); return [...counts].sort((left, right) => right[1] - left[1]).slice(0, 10).map(([keyword, value]) => ({ keyword, count: value })); }, [includeStopWords, result, text]); const max = Math.max(1, ...displayKeywords.map((item) => item.count)); const status = !result || !focusKeyword.trim() ? "Add a focus keyword for optimisation guidance." : result.keyword_density_percent < .5 ? "Increase mentions naturally." : result.keyword_density_percent > 3 ? "Decrease repeated mentions." : "Good keyword usage.";
  return <section><label className="block text-sm font-medium">Text to analyse<textarea value={text} onChange={(event) => setText(event.target.value)} className="mt-1 min-h-56 w-full rounded-xl border border-slate-300 bg-white p-4 dark:border-slate-700 dark:bg-slate-900" /></label><div className="mt-4 grid gap-4 sm:grid-cols-[1fr_auto]"><label className="text-sm font-medium">Focus keyword <span className="font-normal text-slate-500">(optional)</span><input value={focusKeyword} onChange={(event) => setFocusKeyword(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-3 dark:border-slate-700 dark:bg-slate-900" /></label><label className="flex items-end gap-2 text-sm"><input checked={includeStopWords} type="checkbox" onChange={(event) => setIncludeStopWords(event.target.checked)} /> Include stop words</label></div><p className="mt-2 text-sm text-slate-500">{count} words</p>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}{result && <div aria-live="polite" className="mt-6"><div className="rounded-xl border border-indigo-200 bg-indigo-50 p-5 dark:border-indigo-900 dark:bg-indigo-950/40"><p className="text-sm text-slate-500">Focus-keyword density</p><p className="mt-1 text-3xl font-bold">{result.keyword_density_percent}%</p><p className="mt-2 font-medium">{status}</p></div><div className="mt-6 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex justify-between gap-3"><h2 className="font-semibold">Top keywords</h2><button type="button" onClick={() => downloadCsv("keyword-density.csv", csv([["Keyword", "Count"], ...displayKeywords.map((item) => [item.keyword, item.count])]))} className="text-sm font-medium text-indigo-600">Export CSV</button></div><ol className="mt-4 grid gap-3">{displayKeywords.map((item) => <li key={item.keyword}><div className="mb-1 flex justify-between text-sm"><span>{item.keyword}</span><span>{item.count}</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-indigo-600" style={{ width: `${item.count / max * 100}%` }} /></div></li>)}</ol></div><div className="mt-6 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">Recommendations</h2><ul className="mt-3 grid gap-2 text-sm">{result.recommendations.map((recommendation) => <li key={recommendation}>✓ {recommendation}</li>)}</ul></div></div>}</section>;
}
