import { useEffect, useState } from "react";
import { calculate } from "../../api/client";
import { trackToolUsed } from "../../analytics/ga4";
import { MIN_WORDS, words } from "./seoUtils";
import type { JsonValue } from "../../types";

interface Readability { flesch_reading_ease: number; flesch_kincaid_grade: number; gunning_fog: number; coleman_liau: number; smog_grade: number; uk_grade_level: string; recommendations: string[]; }
const sample = "Clear writing helps readers understand important information quickly. Use shorter sentences, direct language, and useful examples to make content easier to scan and remember.";
export function ReadabilityScoreTool(): JSX.Element {
  const [text, setText] = useState(sample); const [result, setResult] = useState<Readability | null>(null); const [technical, setTechnical] = useState(false); const [error, setError] = useState(""); const count = words(text).length;
  useEffect(() => { if (count < MIN_WORDS) { setResult(null); return; } const timer = window.setTimeout(() => void calculate<Readability & Record<string, JsonValue>>("/api/v1/tools/seo/readability-score", { text }).then((response) => { setResult(response.result); setError(""); trackToolUsed("seo", "readability-score", response.result); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Scores are unavailable.")), 400); return () => window.clearTimeout(timer); }, [count, text]);
  const interpretation = !result ? "Add more text to score readability." : result.flesch_reading_ease >= 60 ? "Easy to read for a broad online audience." : "Consider shorter sentences and simpler vocabulary.";
  return <section><label className="block text-sm font-medium">Text to analyse<textarea value={text} onChange={(event) => setText(event.target.value)} className="mt-1 min-h-56 w-full rounded-xl border border-slate-300 bg-white p-4 dark:border-slate-700 dark:bg-slate-900" /></label><p className="mt-2 text-sm text-slate-500">{count} words</p>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}{result && <div aria-live="polite" className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-xl border border-indigo-200 bg-indigo-50 p-6 dark:border-indigo-900 dark:bg-indigo-950/40"><p className="text-sm text-slate-600 dark:text-slate-300">Flesch reading ease</p><p className="mt-1 text-5xl font-bold">{result.flesch_reading_ease}</p><p className="mt-3">{interpretation}</p><button type="button" aria-expanded={technical} onClick={() => setTechnical((value) => !value)} className="mt-5 text-sm font-semibold text-indigo-600">{technical ? "Hide" : "Show"} technical scores</button>{technical && <dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Score label="Flesch–Kincaid" value={result.flesch_kincaid_grade} /><Score label="Gunning Fog" value={result.gunning_fog} /><Score label="Coleman–Liau" value={result.coleman_liau} /><Score label="SMOG grade" value={result.smog_grade} /><Score label="UK grade" value={result.uk_grade_level} /></dl>}</div><Radar result={result} /><div className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 lg:col-span-2"><h2 className="font-semibold">Recommended next steps</h2><ul className="mt-3 grid gap-2">{result.recommendations.map((recommendation) => <li key={recommendation} className="rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800">✓ {recommendation}</li>)}</ul></div></div>}</section>;
}
function Score({ label, value }: { label: string; value: string | number }): JSX.Element { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="font-semibold">{value}</dd></div>; }
function Radar({ result }: { result: Readability }): JSX.Element { const axes = [Math.min(100, result.flesch_reading_ease), Math.min(100, result.flesch_kincaid_grade * 8), Math.min(100, result.gunning_fog * 7), Math.min(100, result.coleman_liau * 8), Math.min(100, result.smog_grade * 8)]; const points = axes.map((value, index) => { const angle = -Math.PI / 2 + index * Math.PI * 2 / axes.length; const radius = value * .8; return `${100 + Math.cos(angle) * radius},${100 + Math.sin(angle) * radius}`; }).join(" "); return <figure className="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><figcaption className="font-semibold">Readability profile</figcaption><svg viewBox="0 0 200 200" role="img" aria-label="Radar chart comparing readability scores" className="mx-auto mt-3 w-full max-w-64"><circle cx="100" cy="100" r="80" fill="none" stroke="currentColor" className="text-slate-200 dark:text-slate-700" /><circle cx="100" cy="100" r="40" fill="none" stroke="currentColor" className="text-slate-200 dark:text-slate-700" /><polygon points={points} fill="rgba(79,70,229,.25)" stroke="#4f46e5" strokeWidth="2" /></svg><p className="text-center text-xs text-slate-500">Flesch · FK · Fog · Coleman · SMOG</p></figure>; }
