import { useEffect, useMemo, useState } from "react";
import { calculate } from "../../api/client";
import { trackToolUsed } from "../../analytics/ga4";
import { csv, downloadCsv, MIN_WORDS, words } from "./seoUtils";
import type { JsonValue } from "../../types";

interface WordStats { word_count: number; char_count: number; char_count_no_spaces: number; sentence_count: number; paragraph_count: number; reading_time_minutes: number; frequency_map: Record<string, number>; }
export function WordCounterTool(): JSX.Element {
  const [text, setText] = useState(""); const [stats, setStats] = useState<WordStats | null>(null); const [error, setError] = useState(""); const count = words(text).length;
  useEffect(() => { if (count < MIN_WORDS) { setStats(null); return; } const timer = window.setTimeout(() => { void calculate<WordStats & Record<string, JsonValue>>("/api/v1/tools/seo/word-counter", { text }).then((response) => { setStats(response.result); setError(""); trackToolUsed("seo", "word-counter", response.result); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Analysis is unavailable.")); }, 350); return () => window.clearTimeout(timer); }, [count, text]);
  const frequent = useMemo(() => Object.entries(stats?.frequency_map ?? {}).sort(([, left], [, right]) => right - left).slice(0, 10), [stats]);
  async function paste(): Promise<void> { try { setText(await navigator.clipboard.readText()); } catch { setError("Clipboard access was blocked. Paste with your keyboard instead."); } }
  return <section><label className="block text-sm font-medium">Text to analyse<textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Start writing or paste text here…" className="mt-1 min-h-56 w-full rounded-xl border border-slate-300 bg-white p-4 dark:border-slate-700 dark:bg-slate-900" aria-describedby="word-count" /></label><div id="word-count" className="mt-2 flex flex-wrap justify-between gap-2 text-sm text-slate-500"><span>{count.toLocaleString()} words · {text.length.toLocaleString()} characters</span><span><button type="button" onClick={() => void navigator.clipboard?.writeText(text)} className="underline">Copy text</button> · <button type="button" onClick={() => void paste()} className="underline">Paste</button></span></div>{count > 0 && count < MIN_WORDS && <p className="mt-4 text-sm text-amber-700 dark:text-amber-300">Add {MIN_WORDS - count} more words for full analysis.</p>}{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}{stats && <div aria-live="polite" className="mt-6"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[["Words", stats.word_count], ["Characters", stats.char_count], ["No spaces", stats.char_count_no_spaces], ["Sentences", stats.sentence_count], ["Paragraphs", stats.paragraph_count], ["Reading time", `${stats.reading_time_minutes} min`]].map(([label, value]) => <Stat key={String(label)} label={String(label)} value={String(value)} />)}</div><div className="mt-6 rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><h2 className="font-semibold">Most frequent words</h2><button type="button" onClick={() => downloadCsv("word-frequency.csv", csv([["Word", "Count"], ...frequent]))} className="text-sm font-medium text-indigo-600">Export CSV</button></div><table className="mt-3 w-full text-left text-sm"><thead className="text-slate-500"><tr><th>Word</th><th className="text-right">Count</th></tr></thead><tbody>{frequent.map(([word, frequency]) => <tr key={word} className="border-t border-slate-100 dark:border-slate-800"><td className="py-2">{word}</td><td className="py-2 text-right">{frequency}</td></tr>)}</tbody></table></div></div>}</section>;
}
function Stat({ label, value }: { label: string; value: string }): JSX.Element { return <div className="rounded-xl border border-indigo-200 bg-indigo-50 p-4 dark:border-indigo-900 dark:bg-indigo-950/40"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>; }
