data "aws_iam_policy_document" "ecs_assume" { statement { actions = ["sts:AssumeRole"]; principals { type = "Service"; identifiers = ["ecs-tasks.amazonaws.com"] } } }
resource "aws_iam_role" "task_execution" { name = "${local.name}-execution"; assume_role_policy = data.aws_iam_policy_document.ecs_assume.json }
resource "aws_iam_role_policy_attachment" "task_execution" { role = aws_iam_role.task_execution.name; policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy" }
resource "aws_iam_role" "task" { name = "${local.name}-task"; assume_role_policy = data.aws_iam_policy_document.ecs_assume.json }
resource "aws_iam_role_policy" "task" { role = aws_iam_role.task.id; policy = jsonencode({ Version = "2012-10-17", Statement = [{ Effect = "Allow", Action = ["cloudwatch:PutMetricData"], Resource = "*" }] }) }
data "aws_iam_policy_document" "github_assume" { statement { actions = ["sts:AssumeRoleWithWebIdentity"]; principals { type = "Federated"; identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:oidc-provider/token.actions.githubusercontent.com"] }; condition { test = "StringEquals"; variable = "token.actions.githubusercontent.com:aud"; values = ["sts.amazonaws.com"] }; condition { test = "StringLike"; variable = "token.actions.githubusercontent.com:sub"; values = ["repo:${var.github_repository}:ref:refs/heads/main"] } } }
data "aws_caller_identity" "current" {}
resource "aws_iam_role" "github" { name = "${local.name}-github-deploy"; assume_role_policy = data.aws_iam_policy_document.github_assume.json }
resource "aws_iam_role_policy" "github" { role = aws_iam_role.github.id; policy = jsonencode({ Version = "2012-10-17", Statement = [{ Effect = "Allow", Action = ["ecr:GetAuthorizationToken"], Resource = "*" }, { Effect = "Allow", Action = ["ecr:BatchCheckLayerAvailability", "ecr:InitiateLayerUpload", "ecr:UploadLayerPart", "ecr:CompleteLayerUpload", "ecr:PutImage", "ecs:Describe*", "ecs:RegisterTaskDefinition", "ecs:UpdateService"], Resource = "*" }] }) }
